osx_image: xcode7
language: objective-c
branches:
  only:
  - master
  - develop
  - /^feature\/\w+/
env:
  global:
  - BUILD_NUM=$TRAVIS_BUILD_NUMBER
  - PROJECT_REPO_SLUG=$TRAVIS_REPO_SLUG
  - GIT_BRANCH=$TRAVIS_BRANCH
  matrix:
  - PLATFORM=android
  - PLATFORM=ios
before_install:
- brew update || brew update
- brew install git-lfs && git-lfs install && git-lfs pull
- rvm use 2.3.1 --install --disable-binary
- sudo easy_install pip && sudo pip install awscli
- aws s3 cp s3://${AWS_S3_BUCKET}/${PROJECT_REPO_SLUG}/persistent.tar.bz2 - | tar jxf -
- nvm install 6.7.0
- node -v
- npm -v
- ruby --version
install:
- gem install bundler --no-document
- bundle install
- (npm install || npm install) && npm install -g ionic cordova
- test "$PLATFORM" != "android" || brew install android && export ANDROID_HOME=$(brew --prefix android)
script:
- fastlane $PLATFORM build
notifications:
  email: false
  slack:
    secure: Zs10PQbFBbsgpnEsEaUzp/9JAmpDPZnyO2UVBrXueBmjbGYetmdgV+TvFLw8im+kazDLjbKXh20UPOzGxLN0/Nw7mnkSAZCd97gqiYug5XeRvIIf3eakTjfwZTI0OE65L6GGQw3Ba2bG9cI8cpfuiK8M0ZkbO2CsJkNuD5RoboqhafYYCGVqB/hgBkfpMwkBvxsNtmjeWcx9KnOCugto6KSu/rSCIfMYsDKSl3f9cbm4zU7HOSBAKfE2aprAYR50ZzuP4pMOAmnGmfSImJSbsPs/aRx7hKsaA0qsIcz2mOHyVVtg5VQS4x/Cigd0G/726+wuyVBKAj46bD42TzlOEebF5q98hD/4vtSHPP71c2/SIYQD5SmBBVTRolXvGEsoNRMILwD24ZAwXc/pIn+oRmClRoP4R53CnSQbfcBTSRngm4IC69YqKmOV845JRhgmVws8cjLI+qq9JBysBepVn8p6PL+kRYg08SAvRFBulncsM+kRwRZrT5IgsCqoOF0unKQE5xMm/GjqFPFPxv0sIhD/nHXjii43ADpMXHyaGPxf1dXN/6Mvs1p3RBvA+qjKMZTeCEQTwoJ65c+473yMWJoWO6aUygIRoOFIZ/f/rKSOi8XLNoUNlXkV8My72NRM9NTW0n/iDfUXIZDelHpGyt1E0z9xIRa6keTk5+t78NY=
